project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: projects.qmd
        text: Projects

      - href: blog.qmd
        text: Blog

      - href: about.qmd
        text: About

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/olawale-olaniyan/

      - icon: github
        href: https://github.com/DataWale

format:
  html:
    theme: minty
    css: styles.css
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet">
