project:
  type: website
  output-dir: docs

website:
  title: "Olawale Olaniyan"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: projects.qmd
        text: Projects

      - href: blog.qmd
        text: Blog

      - href: about.qmd
        text: About

format:
  html:
    theme: minty
    css: styles.css
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet">
